### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-less#34]
* [x] Use @types, update dependencies and target plugin only for VS Code 1.8.0 and above
  * [ ] Code refactoring
    * [ ] Use classes for parser, providers and services
    * [ ] Simplify Completion and SignatureHelp provider
    * [ ] Scanner optimization (if it's possible)
    * [ ] Cache -> Storage
  * [ ] Remove autocomplete for Variables and Mixins inside current document (covered by VS Code, fix #27)
  * [ ] Fix problem with update cache from current document
  * [ ] Add support for `@a : 1;`
  * [ ] Remove `preview` status
  * [ ] May be add support foe "Find All References to a Symbol" (#30)
